#use of try and except
try:
    print(x)
 
except NameError:
    print("there is an error")